name: HTML CI

on:
  push:
    branches: [ "main" ]

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check index file
        run: test -f index.html

      - name: Success message
        run: echo "CI Passed ✔"
